version: '3'
services:
  php:
    build:
      context: ./docker/php/
    volumes:
    - './src:/var/www/html'
    links:
    - mysql

  apache:
    image: httpd:latest
    ports:
    - 80:80
    volumes:
      - './src:/var/www/html'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=8hXI5MgIbqifZ
      - MYSQL_DATABASE=webinar_bd
      - MYSQL_HOST=127.0.0.1
    ports:
      - 3306:3306
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './db/init.sql:/webinar_bd.sql'
