version: '3'
services:
  php:
    build:
      context: ./docker/php/
    volumes:
      - './src:/var/www/html'
    links:
      - mysql

  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=8hXI5MgIbqifZ
      - MYSQL_DATABASE=webinar_bd
    ports:
      - 3306:3306
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
      - ./db/init.sql:/webinar_bd.sql
