version: '3'
services:
  php:
    build:
      context: ./docker/php/
    ports:
    - 80:80
    volumes:
    - './src:/var/www/html'
    links:
    - mysql

  apache:
    image: httpd:latest
    volumes:
      - ./src:/usr/local/apache2/htdocs

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=8hXI5MgIbqifZ
      - MYSQL_DATABASE=webinar_bd
    ports:
      - 3306:3306
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './db/init.sql:/webinar_bd.sql'
