version: '3'
services:
  php:
    build:
      context: ./docker/php/
    ports:
    - 80:80
    volumes:
    - './src:/var/www/html'

  apache:
    image: httpd:latest
    volumes:
      - './src:/var/www/html'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=8hXI5MgIbqifZ
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './db/init.sql:./webinar_bd.sql'
