---
  - hosts: docker-dev-web
    gather_facts: true
    tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/exSesh/webinar-test.git
        dest: /home/sesh/
        clone: yes
        update: yes

    - name: "start docker compose"
      shell: docker compose -f webinar-test/docker-compose.yml up -d