---
  - hosts: docker-dev-web
    gather_facts: true
    tasks:
    - name: "open project"
      shell: cd /home/sesh/webinar-test/

    - name: "start docker compose"
      shell: docker compose -f docker-compose.yml up -d