---
  - hosts: docker-dev-web
    gather_facts: true
    tasks:
    - name: "git clone"
      shell: git clone https://github.com/exSesh/webinar-test.git
      
    - name: "start docker compose"
      shell: docker compose -f webinar-test/docker-compose.yml up -d