---
  - hosts: docker-dev-web
    gather_facts: true
    tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/exSesh/webinar-test.git
        clone: no
        update: yes

    - name: "start docker compose"
      shell: docker compose -f webinar-test/docker-compose.yml up -d 
#     shell: docker compose -f webinar-test/docker-compose.yml up -d --scale mysql=5

    - name:
      shell: cat webinar-test/webinar_bd.sql | docker exec -i webinar-test-mysql-1 mysql --password=8hXI5MgIbqifZ webinar_bd